/**
 * \file list-mon-race-flags.h
 * \brief monster race flags
 *
 */
/* symbol		type			descr */
RF(NONE,		RFT_NONE,		"")
RF(UNIQUE,		RFT_OBV,		"")
RF(QUESTOR,		RFT_OBV,		"")
RF(MALE,		RFT_OBV,		"")
RF(FEMALE,		RFT_OBV,		"")
RF(GROUP_AI,	RFT_OBV,		"")
RF(NAME_COMMA,	RFT_OBV,		"")
RF(CHAR_CLEAR,	RFT_DISP,		"")
RF(ATTR_RAND,	RFT_DISP,		"")
RF(ATTR_CLEAR,	RFT_DISP,		"")
RF(ATTR_MULTI,	RFT_DISP,		"")
RF(ATTR_FLICKER,RFT_DISP,		"")
RF(FORCE_DEPTH,	RFT_GEN,		"")
RF(FORCE_SLEEP,	RFT_GEN,		"")
RF(FORCE_EXTRA,	RFT_GEN,		"")
RF(SEASONAL,	RFT_GEN,		"")
RF(UNAWARE,		RFT_NOTE,		"")
RF(MULTIPLY,	RFT_NOTE,		"")
RF(REGENERATE,	RFT_NOTE,		"")
RF(FRIGHTENED,	RFT_BEHAV,		"")
RF(NEVER_BLOW,	RFT_BEHAV,		"")
RF(NEVER_MOVE,	RFT_BEHAV,		"")
RF(RAND_25,		RFT_BEHAV,		"")
RF(RAND_50,		RFT_BEHAV,		"")
RF(MIMIC_INV,	RFT_BEHAV,		"")
RF(STUPID,		RFT_BEHAV,		"")
RF(SMART,		RFT_BEHAV,		"")
RF(SPIRIT,		RFT_BEHAV,		"")
RF(POWERFUL,	RFT_BEHAV,		"")
RF(ONLY_GOLD,	RFT_DROP,		"")
RF(ONLY_ITEM,	RFT_DROP,		"")
RF(DROP_40,		RFT_DROP,		"")
RF(DROP_60,		RFT_DROP,		"")
RF(DROP_1,		RFT_DROP,		"")
RF(DROP_2,		RFT_DROP,		"")
RF(DROP_3,		RFT_DROP,		"")
RF(DROP_4,		RFT_DROP,		"")
RF(DROP_GOOD,	RFT_DROP,		"")
RF(DROP_GREAT,	RFT_DROP,		"")
RF(DROP_20,		RFT_DROP,		"")
// RF(INVISIBLE,	RFT_DET,		"invisible")
RF(INVISIBLE,	RFT_DET,		"невидимый")
// RF(COLD_BLOOD,	RFT_DET,		"cold blooded")
RF(COLD_BLOOD,	RFT_DET,		"безжалостный")
// RF(EMPTY_MIND,	RFT_DET,		"not detected by telepathy")
RF(EMPTY_MIND,	RFT_DET,		"не обнаруживается телепатией")
// RF(WEIRD_MIND,	RFT_DET,		"rarely detected by telepathy")
RF(WEIRD_MIND,	RFT_DET,		"редко обнаруживается телепатией")
// RF(OPEN_DOOR,	RFT_ALTER,		"open doors")
RF(OPEN_DOOR,	RFT_ALTER,		"открывать двери")
// RF(BASH_DOOR,	RFT_ALTER,		"bash down doors")
RF(BASH_DOOR,	RFT_ALTER,		"вышибать двери")
// RF(PASS_WALL,	RFT_ALTER,		"pass through walls")
RF(PASS_WALL,	RFT_ALTER,		"проходить сквозь стены")
// RF(KILL_WALL,	RFT_ALTER,		"bore through walls")
RF(KILL_WALL,	RFT_ALTER,		"проникать сквозь стены")
// RF(SMASH_WALL,	RFT_ALTER,		"smash walls")
RF(SMASH_WALL,	RFT_ALTER,		"крушить стены")
// RF(MOVE_BODY,	RFT_ALTER,		"push past weaker monsters")
RF(MOVE_BODY,	RFT_ALTER,		"толкать в сторону более слабых монстров")
// RF(KILL_BODY,	RFT_ALTER,		"destroy weaker monsters")
RF(KILL_BODY,	RFT_ALTER,		"уничтожать более слабых монстров")
// RF(TAKE_ITEM,	RFT_ALTER,		"pick up objects")
RF(TAKE_ITEM,	RFT_ALTER,		"поднимать предметы")
// RF(KILL_ITEM,	RFT_ALTER,		"destroy objects")
RF(KILL_ITEM,	RFT_ALTER,		"уничтожать предметы")
// RF(CLEAR_WEB,	RFT_ALTER,		"clear webs")
RF(CLEAR_WEB,	RFT_ALTER,		"расчищать паутину")
// RF(PASS_WEB,	RFT_ALTER,		"pass through webs")
RF(PASS_WEB,	RFT_ALTER,		"проходить сквозь паутину")
// RF(ORC,			RFT_RACE_N,		"orc")
RF(ORC,			RFT_RACE_N,		"орк")
// RF(TROLL,		RFT_RACE_N,		"troll")
RF(TROLL,		RFT_RACE_N,		"тролль")
// RF(GIANT,		RFT_RACE_N,		"giant")
RF(GIANT,		RFT_RACE_N,		"гигант")
// RF(DRAGON,		RFT_RACE_N,		"dragon")
RF(DRAGON,		RFT_RACE_N,		"дракон")
// RF(DEMON,		RFT_RACE_N,		"demon")
RF(DEMON,		RFT_RACE_N,		"демон")
// RF(ANIMAL,		RFT_RACE_A,		"natural")
RF(ANIMAL,		RFT_RACE_A,		"природный")
// RF(EVIL,		RFT_RACE_A,		"evil")
RF(EVIL,		RFT_RACE_A,		"злой")
// RF(UNDEAD,		RFT_RACE_A,		"undead")
RF(UNDEAD,		RFT_RACE_A,		"немёртвый")
// RF(NONLIVING,	RFT_RACE_A,		"nonliving")
RF(NONLIVING,	RFT_RACE_A,		"неживой")
// RF(METAL,		RFT_RACE_A,		"metal")
RF(METAL,		RFT_RACE_A,		"металлический")
// RF(HURT_LIGHT,	RFT_VULN,		"bright light")
RF(HURT_LIGHT,	RFT_VULN,		"яркому свету")
// RF(HURT_ROCK,	RFT_VULN,		"rock remover")
RF(HURT_ROCK,	RFT_VULN,		"камнетёсу")
// RF(HURT_FIRE,	RFT_VULN_I,		"fire")
RF(HURT_FIRE,	RFT_VULN_I,		"огню")
// RF(HURT_COLD,	RFT_VULN_I,		"cold")
RF(HURT_COLD,	RFT_VULN_I,		"холоду")
// RF(IM_ACID,		RFT_RES,		"acid")
RF(IM_ACID,		RFT_RES,		"кислоте")
// RF(IM_ELEC,		RFT_RES,		"lightning")
RF(IM_ELEC,		RFT_RES,		"молниям")
// RF(IM_FIRE,		RFT_RES,		"fire")
RF(IM_FIRE,		RFT_RES,		"огню")
// RF(IM_COLD,		RFT_RES,		"cold")
RF(IM_COLD,		RFT_RES,		"холоду")
// RF(IM_POIS,		RFT_RES,		"poison")
RF(IM_POIS,		RFT_RES,		"яду")
// RF(IM_NETHER,	RFT_RES,		"nether")
RF(IM_NETHER,	RFT_RES,		"подземному мраку")
// RF(IM_WATER,	RFT_RES,		"water")
RF(IM_WATER,	RFT_RES,		"воде")
// RF(IM_PLASMA,	RFT_RES,		"plasma")
RF(IM_PLASMA,	RFT_RES,		"плазме")
// RF(IM_NEXUS,	RFT_RES,		"nexus")
RF(IM_NEXUS,	RFT_RES,		"смещению")
// RF(IM_DISEN,	RFT_RES,		"disenchantment")
RF(IM_DISEN,	RFT_RES,		"развоплощению")
// RF(NO_FEAR,		RFT_PROT,		"frightened")
RF(NO_FEAR,		RFT_PROT,		"испугу")
// RF(NO_STUN,		RFT_PROT,		"stunned")
RF(NO_STUN,		RFT_PROT,		"ошеломлению")
// RF(NO_CONF,		RFT_PROT,		"confused")
RF(NO_CONF,		RFT_PROT,		"замешательству")
// RF(NO_SLEEP,	RFT_PROT,		"slept")
RF(NO_SLEEP,	RFT_PROT,		"усыплению")
// RF(NO_HOLD,		RFT_PROT,		"held")
RF(NO_HOLD,		RFT_PROT,		"захвату контроля")
// RF(NO_SLOW,		RFT_PROT,		"slowed")
RF(NO_SLOW,		RFT_PROT,		"замедлению")
/* end flags */
