/**
 * \file list-ignore-types.h
 * \brief types of object used for ignoring by quality or ego
 */

/* index					description */
ITYPE(NONE,					"")
// ITYPE(SHARP,				"Sharp Melee Weapons")
ITYPE(SHARP,				"Острое Оружие Ближнего Боя")
// ITYPE(BLUNT,				"Blunt Melee Weapons")
ITYPE(BLUNT,				"Тупое Оружие Ближнего Боя")
// ITYPE(GREAT,				"Great Weapons")
ITYPE(GREAT,				"Великое Оружие")
// ITYPE(SLING,				"Slings")
ITYPE(SLING,				"Пращи")
// ITYPE(BOW,					"Bows")
ITYPE(BOW,					"Луки")
// ITYPE(CROSSBOW,				"Crossbows")
ITYPE(CROSSBOW,				"Арбалеты")
// ITYPE(SHOT,					"Shots and Pebbles")
ITYPE(SHOT,					"Выстрелы и Камушки")
// ITYPE(ARROW,				"Arrows")
ITYPE(ARROW,				"Стрелы")
// ITYPE(BOLT,					"Bolts")
ITYPE(BOLT,					"Болты")
// ITYPE(ROBE,					"Robes")
ITYPE(ROBE,					"Мантии")
// ITYPE(BODY_ARMOR,			"Body Armor")
ITYPE(BODY_ARMOR,			"Нательная Броня")
// ITYPE(BASIC_DRAGON_ARMOR,	"Basic Dragon Scale Mail")
ITYPE(BASIC_DRAGON_ARMOR,	"Базовая Драконья Броня")
// ITYPE(MULTI_DRAGON_ARMOR,	"Multi-Hued Dragon Scale Mail")
ITYPE(MULTI_DRAGON_ARMOR,	"Многоцветная Драконья Броня")
// ITYPE(HIGH_DRAGON_ARMOR,	"High Dragon Scale Mail")
ITYPE(HIGH_DRAGON_ARMOR,	"Высшая Драконья Броня")
// ITYPE(BALANCE_DRAGON_ARMOR,	"Balance Dragon Scale Mail")
ITYPE(BALANCE_DRAGON_ARMOR,	"Сбалансированная Драконья Броня")
// ITYPE(POWER_DRAGON_ARMOR,	"Power Dragon Scale Mail")
ITYPE(POWER_DRAGON_ARMOR,	"Силовая Драконья Броня")
// ITYPE(CLOAK,				"Cloaks")
ITYPE(CLOAK,				"Плащи")
// ITYPE(ELVEN_CLOAK,			"Elven Cloaks")
ITYPE(ELVEN_CLOAK,			"Эльфийские Плащи")
// ITYPE(SHIELD,				"Shields")
ITYPE(SHIELD,				"Щиты")
// ITYPE(HEADGEAR,				"Headgear")
ITYPE(HEADGEAR,				"Головные Уборы")
// ITYPE(HANDGEAR,				"Handgear")
ITYPE(HANDGEAR,				"Перчатки")
// ITYPE(FEET,					"Footgear")
ITYPE(FEET,					"Обувь")
// ITYPE(DIGGER,				"Diggers")
ITYPE(DIGGER,				"Копатели")
// ITYPE(RING,					"Rings")
ITYPE(RING,					"Кольца")
// ITYPE(AMULET,				"Amulets")
ITYPE(AMULET,				"Амулеты")
// ITYPE(LIGHT, 				"Lights")
ITYPE(LIGHT, 				"Освещение")
